[package]
name = "derive_macros"
version = "0.1.0"
authors = ["BB20101997 <bennet-blessmann@t-online.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.52"
syn = "1.0.109"
quote = "1.0.26"
